### ISSUE TITLE
Move issues when migrating from Org to Repo level Projects

### ISSUE THREAD

**Issue by Chocrates** [froi/github-project-migrator#17]
__Is your feature request related to a problem? Please describe.__
When attempting to move an Org project to a new repo, if the Org project has issues from a repo, it will fail with this error: 

```
(node:39621) UnhandledPromiseRejectionWarning: GraphqlError: contentID must refer to an issue or pull request in the same repository as the project
```

__Describe the solution you'd like__
I would like the ability to have the migrator migrate issues when it is required.

__Describe alternatives you've considered__
Writing a custom script to move the issues and then use this to migrate the board.

**Comment by froi** [comment]
Thanks for the issue @Chocrates 

I'm assuming that the project board at the Org level has issues that belong to different repos than the target. Would the use case be to create/migrate the issues in the target repo?

**Comment by Chocrates** [comment]
Yep!
